import fs from 'fs';
import path from 'path';
import { CONTENT_ROOT, OBJECTIVE_KEY_DIR, REPO_ROOT, loadPackageFolder } from '../lib/lesson-package/files';
import type { LessonPackage } from '../lib/lesson-package/schema';

const USAGE = `Coverage of the Mastery Advantage graph per level (track level_banks_20261002).

Usage: npx tsx scripts/level-coverage.ts [--out <file.md>]

For each of the levels 1–4: the packages of the level (workbook books and the bank), each objective
of the level's own GSE range with the count of packages that target it (tags.targetObjectives) and
of questions that test it, and the share of the level's word list that the packages gloss. The
letter and sound objectives are out of scope (Daniel, 2026-10-02: schools and Storytime Advantage).
Default output: docs/content-plans/level-plans/coverage.md.`;

/** Book folders per level. Origins 3.1 lessons 1–11, 13, 14 are stored at level 2 in the app. */
const LEVEL_BOOKS: Record<number, string[]> = { 1: ['origins-1', 'bank-1'], 2: ['origins-2', 'bank-2'], 3: ['origins-3.1', 'origins-3.2', 'bank-3'], 4: ['quest-4', 'bank-4'] };
const GSE: Record<number, [number, number]> = { 1: [10, 13], 2: [14, 17], 3: [18, 21], 4: [22, 23] };
const OUT_OF_SCOPE = new Set(['R10.1', 'R10.3', 'R14.2', 'R18.1', 'R21.3', 'L10.1', 'L10.3', 'L10.5', 'L16.3']);
const MIN_TARGETS = 2;

interface Objective {
    id: string;
    gse: number;
    text: string;
}

function readObjectives(): Objective[] {
    return fs
        .readdirSync(OBJECTIVE_KEY_DIR)
        .filter((f) => f.endsWith('-objective-key.json'))
        .flatMap((f) => (JSON.parse(fs.readFileSync(path.join(OBJECTIVE_KEY_DIR, f), 'utf8')) as { objectives: Objective[] }).objectives);
}

function readWords(file: string): Set<string> {
    const out = new Set<string>();
    for (const line of fs.readFileSync(file, 'utf8').split('\n')) {
        if (line.startsWith('#') || !line.trim()) continue;
        for (const w of line.split(',')) if (/^[a-z' -]+$/.test(w.trim())) out.add(w.trim());
    }
    return out;
}

function main(argv: string[]): number {
    if (argv.includes('--help')) {
        console.log(USAGE);
        return 0;
    }
    const outAt = argv.indexOf('--out');
    const out = outAt >= 0 ? path.resolve(argv[outAt + 1]) : path.join(REPO_ROOT, 'docs/content-plans/level-plans/coverage.md');
    const objectives = readObjectives();
    const data = path.join(REPO_ROOT, 'docs/content-plans/data');
    const starters = readWords(path.join(data, 'yle-starters-words.md'));
    const movers = readWords(path.join(data, 'yle-movers-words.md'));
    const md = ['# Levels 1–4: coverage of the Mastery Advantage graph', '', `Generated by \`dashboard/scripts/level-coverage.ts\` on ${new Date().toISOString().slice(0, 10)} (track level_banks_20261002). A package counts for an objective when the objective is in its targets. The letter and sound objectives are out of scope (schools and Storytime Advantage). Goal: every in-scope objective of a level's own range is a target in ${MIN_TARGETS} or more packages.`, ''];
    let gaps = 0;
    for (const level of [1, 2, 3, 4]) {
        const pkgs: LessonPackage[] = LEVEL_BOOKS[level].flatMap((b) => loadPackageFolder(path.join(CONTENT_ROOT, b)).flatMap((f) => (f.pkg && f.pkg.meta.raLevel === level ? [f.pkg] : [])));
        const [lo, hi] = GSE[level];
        const own = objectives.filter((o) => o.gse >= lo && o.gse <= hi && !OUT_OF_SCOPE.has(o.id));
        const targetCount = new Map<string, number>();
        const questionCount = new Map<string, number>();
        for (const p of pkgs) {
            for (const id of new Set(p.tags.targetObjectives)) targetCount.set(id, (targetCount.get(id) ?? 0) + 1);
            for (const q of [...p.bank.mcq, ...p.bank.saq, ...p.bank.laq]) for (const id of q.objectives) questionCount.set(id, (questionCount.get(id) ?? 0) + 1);
        }
        const list = level === 4 ? movers : starters;
        const glossed = new Set(pkgs.flatMap((p) => p.text.glossed.map((g) => g.toLowerCase())));
        const onList = [...list].filter((w) => glossed.has(w)).length;
        const low = own.filter((o) => (targetCount.get(o.id) ?? 0) < MIN_TARGETS);
        gaps += low.length;
        md.push(`## Level ${level} (GSE ${lo}–${hi})`, '', `${pkgs.length} packages (${LEVEL_BOOKS[level].join(', ')}). Glossed: ${glossed.size} different words; ${onList} of the ${list.size} ${level === 4 ? 'Movers' : 'Starters'} words. ${low.length ? `${low.length} objective(s) under ${MIN_TARGETS} packages.` : 'Every in-scope objective has enough packages.'}`, '', '| Objective | Packages (target) | Questions | Text |', '|---|---|---|---|');
        for (const o of own) md.push(`| ${o.id} | ${targetCount.get(o.id) ?? 0}${(targetCount.get(o.id) ?? 0) < MIN_TARGETS ? ' ⚠' : ''} | ${questionCount.get(o.id) ?? 0} | ${o.text} |`);
        md.push('');
        console.log(`level ${level}: ${pkgs.length} packages; ${own.length - low.length} of ${own.length} objectives at ${MIN_TARGETS}+; glossed ${onList} of ${list.size} list words`);
    }
    fs.writeFileSync(out, `${md.join('\n')}\n`);
    console.log(`Wrote ${path.relative(process.cwd(), out)}`);
    return gaps ? 1 : 0;
}

process.exitCode = main(process.argv.slice(2));
