import { test, expect } from '@playwright/test';

test.describe('Compile Flow - Sections Toggling', () => {
  test('should allow toggling compilation sections', async ({ page }) => {
    test.setTimeout(120000); // Compiling all lessons + Paged.js takes time
    // Navigate to projects page
    await page.goto('/projects');
    
    // Wait for projects to load (either secondary or primary)
    const projectLink = page.locator('a[href^="/projects/"]:not([href*="test-"])').first();
    
    await Promise.race([
      page.waitForSelector('a[href^="/projects/"]:not([href*="test-"])'),
      page.waitForSelector('text=No secondary workbook projects found')
    ]);

    const count = await projectLink.count();
    if (count === 0) {
      await page.getByRole('button', { name: /Primary/i }).click();
      await page.waitForSelector('a[href^="/projects/"]:not([href*="test-"])');
    }

    // Click the first project
    await page.locator('a[href^="/projects/"]:not([href*="test-"])').first().click();
    
    // Should be on the project details page
    await expect(page).toHaveURL(/.*\/projects\/[^\/]+/);
    
    // Click "Compile All"
    const compileLink = page.getByRole('link', { name: /Compile All/i });
    await expect(compileLink).toBeVisible();
    await compileLink.click();
    
    // Should be on the compile page
    await expect(page).toHaveURL(/.*\/compile/);
    
    // Open settings panel
    const settingsButton = page.getByTitle('Compilation Settings');
    await expect(settingsButton).toBeVisible();
    await settingsButton.click();
    
    // Verify all checkboxes exist. Flashcards, self-assessment, and goal setting are off by
    // default (2026-10-02: fewer non-lesson pages in the printed book). The teacher guide is off
    // too (2026-10-03: each workbook gets a separate teacher's manual).
    const onByDefault = [
      'Progress Tracker',
      'Spelling Practice',
      'Certificate'
    ];
    const offByDefault = [
      "Teacher's Guide",
      'Vocabulary Flashcards',
      'Self-Assessment',
      'Goal Setting'
    ];

    for (const section of onByDefault) {
      const checkbox = page.getByLabel(section);
      await expect(checkbox).toBeVisible();
      await expect(checkbox).toBeChecked();
    }
    for (const section of offByDefault) {
      const checkbox = page.getByLabel(section);
      await expect(checkbox).toBeVisible();
      await expect(checkbox).not.toBeChecked();
    }

    // Check one and ensure it triggers re-compile (iframe should reload)
    // We can't easily detect iframe reload directly without observing network,
    // but we can ensure the checkbox can be checked and unchecked.
    const goalSettingCheckbox = page.getByLabel('Goal Setting');

    // Check and wait for compile request
    await Promise.all([
      page.waitForResponse(/.*\/api\/projects\/.*\/compile.*/),
      goalSettingCheckbox.check()
    ]);
    await expect(goalSettingCheckbox).toBeChecked();

    // Verify iframe loads again
    await expect(page.locator('iframe')).toBeVisible({ timeout: 60000 });
    
    await expect(page.frameLocator('iframe').locator('body')).toBeVisible({ timeout: 60000 });

    // Check that generated sections appear in the iframe
    const frame = page.frameLocator('iframe');

    // Title Page (usually generated by default)
    await expect(frame.locator('.cover-page').first()).toBeVisible({ timeout: 60000 });

    // Goal Setting (we just checked it)
    await expect(frame.locator('.section-goal-setting').first()).toBeVisible({ timeout: 60000 });

    // Progress Tracker
    await expect(frame.locator('.section-progress-tracker').first()).toBeVisible({ timeout: 60000 });

    // Glossary
    // NOTE: Glossary and Answer Key require vocabulary/lessons to exist. 
    // Usually the primary/secondary test project has at least one lesson.
    await expect(frame.locator('.section-glossary').first()).toBeVisible({ timeout: 60000 });

    // Answer Key
    await expect(frame.locator('.section-answer-key').first()).toBeVisible({ timeout: 60000 });

    // Flashcards (off by default)
    await expect(frame.locator('.section-flashcards')).toHaveCount(0);

    // Teacher's Guide (off by default)
    await expect(frame.locator('.section-teacher-guide')).toHaveCount(0);

    // Spelling Practice
    await expect(frame.locator('.section-spelling-practice').first()).toBeVisible({ timeout: 60000 });

    // Self-Assessment (off by default)
    await expect(frame.locator('.section-self-assessment')).toHaveCount(0);

    // Certificate
    await expect(frame.locator('.section-certificate').first()).toBeVisible({ timeout: 60000 });
  });
});
